# Generated by Django 4.0.4 on 2022-05-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='EstadoSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sub', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_estado_sub',
            },
        ),
        migrations.CreateModel(
            name='itemsCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=40)),
                ('precio_producto', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='itemsCarrito')),
                ('marca', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'db_itemsCarrito',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('pass_usuario', models.CharField(max_length=20)),
                ('telefono_usuario', models.IntegerField()),
                ('correo_usuario', models.EmailField(max_length=30)),
                ('imagen_usuario', models.ImageField(null=True, upload_to='productos')),
                ('direccion_usuario', models.CharField(max_length=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('estado_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadosub')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('categoria', models.ManyToManyField(related_name='categorias', to='app.categoriaproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
    ]
